/**
 * Post registry.
 *
 * Regenerated by scripts/generate-blog-post.ts whenever a new post is scaffolded.
 * Adding a post by hand:
 *   1. Create `content/blog/posts/<slug>.tsx` that exports `meta: PostMeta`
 *      and a default `Content` React component.
 *   2. Re-run `pnpm blog:new <title>` for any post (it regenerates this file)
 *      or update the imports/array below to match the new file.
 *
 * Posts are sorted by publishedAt at runtime in lib/blog/posts.ts.
 */
import type { ComponentType } from 'react'
import type { PostMeta } from '@/lib/blog/types'

import * as cyclingTrainingForParentsWithLimitedTimePost from './cycling-training-for-parents-with-limited-time'
import * as howToTrainWhenYourScheduleChangesEveryWeekPost from './how-to-train-when-your-schedule-changes-every-week'
import * as shouldITrainWhenMyLegsStillFeelHeavyPost from './should-i-train-when-my-legs-still-feel-heavy'
import * as welcomeToTheSmartertrainingBlogPost from './welcome-to-the-smartertraining-blog'
import * as whyAmIExhaustedAfterZone2RidesPost from './why-am-i-exhausted-after-zone-2-rides'
import * as whyConsistencyBeatsPerfectTrainingWeeksPost from './why-consistency-beats-perfect-training-weeks'
import * as whyRecoveryRecommendationsMatterMoreThanPerfectWorkoutsPost from './why-recovery-recommendations-matter-more-than-perfect-workouts'
import * as whyStaticCyclingPlansFailBusyAthletesPost from './why-static-cycling-plans-fail-busy-athletes'

export interface RegisteredPost {
  meta: PostMeta
  Content: ComponentType
}

export const POSTS: RegisteredPost[] = [
  { meta: cyclingTrainingForParentsWithLimitedTimePost.meta, Content: cyclingTrainingForParentsWithLimitedTimePost.default },
  { meta: howToTrainWhenYourScheduleChangesEveryWeekPost.meta, Content: howToTrainWhenYourScheduleChangesEveryWeekPost.default },
  { meta: shouldITrainWhenMyLegsStillFeelHeavyPost.meta, Content: shouldITrainWhenMyLegsStillFeelHeavyPost.default },
  { meta: welcomeToTheSmartertrainingBlogPost.meta, Content: welcomeToTheSmartertrainingBlogPost.default },
  { meta: whyAmIExhaustedAfterZone2RidesPost.meta, Content: whyAmIExhaustedAfterZone2RidesPost.default },
  { meta: whyConsistencyBeatsPerfectTrainingWeeksPost.meta, Content: whyConsistencyBeatsPerfectTrainingWeeksPost.default },
  { meta: whyRecoveryRecommendationsMatterMoreThanPerfectWorkoutsPost.meta, Content: whyRecoveryRecommendationsMatterMoreThanPerfectWorkoutsPost.default },
  { meta: whyStaticCyclingPlansFailBusyAthletesPost.meta, Content: whyStaticCyclingPlansFailBusyAthletesPost.default },
]
