import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileNameToIdent, POSTS_DIR } from './inventory'

const INDEX_PATH = path.join(POSTS_DIR, 'index.ts')

/**
 * Regenerate `content/blog/posts/index.ts` deterministically from the set of
 * `*.tsx` files in the posts directory. Import order is alphabetical by
 * filename; runtime ordering by publishedAt is handled in lib/blog/posts.ts.
 */
export function regenerateIndex(): { path: string; postCount: number } {
  const files = fs
    .readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith('.tsx'))
    .sort()

  const imports = files.map((f) => {
    const name = path.basename(f, '.tsx')
    const ident = fileNameToIdent(name)
    return `import * as ${ident} from './${name}'`
  })

  const entries = files.map((f) => {
    const name = path.basename(f, '.tsx')
    const ident = fileNameToIdent(name)
    return `  { meta: ${ident}.meta, Content: ${ident}.default },`
  })

  const importsBlock = imports.length > 0 ? imports.join('\n') + '\n' : ''
  const entriesBlock = entries.length > 0 ? entries.join('\n') + '\n' : ''

  const content = `/**
 * Post registry.
 *
 * Regenerated by scripts/generate-blog-post.ts whenever a new post is scaffolded.
 * Adding a post by hand:
 *   1. Create \`content/blog/posts/<slug>.tsx\` that exports \`meta: PostMeta\`
 *      and a default \`Content\` React component.
 *   2. Re-run \`pnpm blog:new <title>\` for any post (it regenerates this file)
 *      or update the imports/array below to match the new file.
 *
 * Posts are sorted by publishedAt at runtime in lib/blog/posts.ts.
 */
import type { ComponentType } from 'react'
import type { PostMeta } from '@/lib/blog/types'

${importsBlock}
export interface RegisteredPost {
  meta: PostMeta
  Content: ComponentType
}

export const POSTS: RegisteredPost[] = [
${entriesBlock}]
`

  fs.writeFileSync(INDEX_PATH, content)
  return { path: INDEX_PATH, postCount: files.length }
}
